apiVersion: v1
description: Foldy Operator is a Kubernetes-native application for protein structure prediction research
name: foldy-operator
version: 0.0.0
appVersion: master
keywords:
- protein
- structure
- prediction
home: https://foldy.dev
sources:
- https://github.com/foldy-project/foldy-operator
maintainers:
- name: Tom
  email: info@foldy.dev
dependencies:
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 5.0.16
    condition: minio.enabled, global.minio.enabled
  - name: argo
    repository: https://argoproj.github.io/argo-helm
    version: 0.7.2
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 1.8.7
  - name: argo-events
    repository: https://argoproj.github.io/argo-helm
    version: 0.7.0
  - name: traefik
    repository: https://containous.github.io/traefik-helm-chart
    version: 6.0.0
    condition: traefik.enabled, global.traefik.enabled
