minio:
  enabled: true
  existingSecret: spaces-secret
  s3gateway:
    replicas: 3
    enabled: true
    serviceEndpoint: https://sfo2.digitaloceanspaces.com

operator:
  image: foldy/foldy-operator:latest

ui:
  image: foldy/foldy-ui:latest

watchNamespace: ci