ingress:
  enabled: true
  letsencrypt:
    email: keres993@gmail.com
  argocd:
    host: argocd.foldy.dev
  events:
    host: events.foldy.dev
  ui:
    host: ui.foldy.dev

operator:
  image: foldy/foldy-operator:latest

ui:
  image: foldy/foldy-ui:latest

ci:
  # Deploys a continuous integration stack that bootstraps
  # chart deployment against a github repo.
  # The webhook is generated for the project automatically, and only
  # the apiToken needs to be populated with a value from Github.
  enabled: true
  github:
    owner: foldy-project
    repository: foldy-operator
    repoURL: https://github.com/foldy-project/foldy-operator.git
    apiToken:
      name: github-access
      key: token
    webhookSecret: # the secret used to create the webhook
      name: github-access
      key: secret
  
minio:
  enabled: false
  #existingSecret: spaces-secret
  #s3gateway:
  #  replicas: 3
  #  enabled: true
  #  serviceEndpoint: https://sfo2.digitaloceanspaces.com

argocd:
  installCRDs: false

argo:
  installCRD: false

events:
  installCRD: false

traefik:
  enabled: true
  additionalArguments:
    - --providers.kubernetesingress=true
    - --providers.kubernetesingress.ingressclass=traefik2

