ingress:
  enabled: true
  argo-cd:
    host: argocd.foldy.dev
    
operator:
  image: foldy/foldy-operator:latest

ui:
  image: foldy/foldy-ui:latest

ci:
  enabled: true
  repository: https://github.com/foldy-project/foldy-operator

minio:
  enabled: false
  #existingSecret: spaces-secret
  #s3gateway:
  #  replicas: 3
  #  enabled: true
  #  serviceEndpoint: https://sfo2.digitaloceanspaces.com

argo-cd:
  installCRDs: false

argo:
  installCRD: false

argo-events:
  installCRD: false

traefik:
  enabled: true
  additionalArguments:
    - --providers.kubernetesingress=true
    - --providers.kubernetesingress.ingressclass=traefik2

