ingress:
  enabled: true
  letsencrypt:
    email: keres993@gmail.com
  argocd:
    host: argocd.foldy.dev
  events:
    host: events.foldy.dev

operator:
  image: foldy/foldy-operator:latest

ui:
  image: foldy/foldy-ui:latest


ci: # deploy continuous integration stack along with application
  enabled: true
  github:
    owner: foldy-project
    repository: foldy-operator
    repoURL: https://github.com/foldy-project/foldy-operator.git
    apiToken:
      name: github-access
      key: token
    webhookSecret:
      name: github-access
      key: secret
  
minio:
  enabled: false
  #existingSecret: spaces-secret
  #s3gateway:
  #  replicas: 3
  #  enabled: true
  #  serviceEndpoint: https://sfo2.digitaloceanspaces.com

argocd:
  installCRDs: false

argo:
  installCRD: false

events:
  installCRD: false

traefik:
  enabled: true
  additionalArguments:
    - --providers.kubernetesingress=true
    - --providers.kubernetesingress.ingressclass=traefik2

