apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-foldy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-foldy-operator
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-foldy-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-foldy-operator
      containers:
        - name: foldy-operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "foldy-operator"
              name: LOCK_NAME
              value: {{ .Release.Name }}-lock