{{- if and .Values.ingress.enabled .Values.ingress.events.enabled }}
# Source: https://www.reddit.com/r/Traefik/comments/d36iry/traefik_20_with_certmanager/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod
    kubernetes.io/ingress.class: fake
  labels:
    traefik2: "true"
  name: {{ .Release.Name }}-events-ingress
spec:
  rules:
  - host: {{ .Values.ingress.events.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-github-gateway-svc
          servicePort: 12000
        path: /
  tls:
  - hosts:
    - {{ .Values.ingress.events.host }}
    secretName: {{ .Release.Name }}-events-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-events-80
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.events.host }}`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}-https-only
      services:
        - name: {{ .Release.Name }}-github-gateway-svc
          port: 12000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-events-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.events.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-github-gateway-svc
          port: 12000
  tls:
    secretName: {{ .Release.Name }}-events-tls
{{- end }}
