apiVersion: apps/v1
kind: Deployment
metadata:
  name: foldy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: foldy-operator
  template:
    metadata:
      labels:
        name: foldy-operator
    spec:
      serviceAccountName: foldy-operator
      containers:
        - name: foldy-operator
          # Replace this with the built image name
          image: foldy/foldy-operator
          command:
          - foldy-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "foldy-operator"
