apiVersion: app.foldy.dev/v1alpha1
kind: Transform
metadata:
  name: example-transform
spec:
  image: foldy/foldy-proteinnet-transform:latest
  imagePullPolicy: IfNotPresent
  replicas: 3
  podSpec:
    # Put arbitrary pod manifest in here. It will be mixed
    # into the deployment, taking precedence.
    resources:
      limits:
        cpu: 250m
