apiVersion: app.foldy.dev/v1alpha1
kind: Backend
metadata:
  name: example-backend
spec:
  image: foldy/foldy-gromacs-backend:latest
  imagePullPolicy: IfNotPresent
  podSpec:
    # Put arbitrary pod manifest in here. It will be mixed
    # into the deployment, taking precedence.
    resources:
      limits:
        cpu: 250m
