apiVersion: app.foldy.dev/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
spec:
  # Defines an example dataset for the wwpdb.org FTP.
  # A minio cache configuration is also provided. The
  # structures will be available 
  type: remote
  source: ftp://ftp.wwpdb.org/pub/pdb/data/structures/all/pdb/
  cache:
    s3:
      endpoint: http://minio:9000
      bucket: wwpdb
      prefix: pdb/ # Put the structures in the pdb/ folder
      accessKeyId:
        valueFrom:
          secretKeyRef:
            name: minio-cred
            key: key
      accessSecret:
        valueFrom:
          secretKeyRef:
            name: minio-cred
            key: secret