apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-foldy-operator-
  namespace: argo-events
spec:
  entrypoint: sync
  arguments:
    parameters:
      - name: info
        value: ""
  templates:
    #- name: build
    #  serviceAccountName: argo-events-sa
    #  inputs:
    #    parameters:
    #      - name: info
    #    artifacts:
    #      - name: my-input-artifact
    #        path: /my-input-artifact
    #        s3:
    #          key: path/in/bucket/my-input-artifact.tgz
    #  container:
    #    image: argoproj/argocd:latest
    #    command: [bash, -c]
    #    args: ["argocd app sync foldy-operator && echo $info"]
    #    env:
    #      - name: info
    #        value: "{{inputs.parameters.info}}"
    #      - name: ARGOCD_SERVER
    #        value: argocd.foldy.dev
    #      - name: ARGOCD_AUTH_TOKEN
    #        valueFrom:
    #          secretKeyRef:
    #            name: argo-token
    #            key: token
    - name: sync
      serviceAccountName: argo-events-sa
      inputs:
        parameters:
          - name: info
      container:
        image: argoproj/argocd:latest
        command: [bash, -c]
        args: ["argocd app sync foldy-operator && echo $info"]
        env:
          - name: info
            value: "{{inputs.parameters.info}}"
          - name: ARGOCD_SERVER
            value: argocd.foldy.dev
          - name: ARGOCD_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: argo-token
                key: token



