apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-foldy-operator-
  namespace: argo-events
spec:
  entrypoint: sync
  arguments:
    parameters:
      - name: message
        value: ""
  templates:
    - name: sync
      serviceAccountName: argo-events-sa
      #inputs:
      #  parameters:
      #    - name: message
      container:
        image: argoproj/argocd:latest
        command: [bash, -c]
        args: ["argocd app sync foldy-operator"]
        env:
          - name: ARGOCD_SERVER
            value: argocd.foldy.dev
          - name: ARGOCD_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: argo-token
                key: token
