apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-foldy-operator-
  namespace: argo-events
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: commit
        value: ""
      - name: modified
        value: ""
  templates:
    - name: main
      serviceAccountName: argo-events-sa
      inputs:
        parameters:
          - name: commit
          - name: modified
      steps:
        - - name: build
            template: build
            arguments:
              parameters:
              - name: commit
                value: "{{inputs.parameters.commit}}"
          - name: dashboard
            template: dashboard
            arguments:
              parameters:
              - name: commit
                value: "{{inputs.parameters.commit}}"
        - - name: sync
            template: sync
            arguments:
              parameters:
              - name: commit
                value: "{{inputs.parameters.commit}}"
              - name: modified
                value: "{{inputs.parameters.modified}}"
    - name: build
      serviceAccountName: argo-events-sa
      inputs:
        parameters:
          - name: commit
        artifacts:
          - name: source
            path: /app
            git:
              repo: https://github.com/foldy-project/foldy-operator.git
      container:
        image: docker:18.09.6
        command: [sh, -c] #
        args:
          [
            echo $commit;
            until docker ps;
              do sleep 3;
            done;
            set -e;
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin;
            docker pull foldy/foldy-operator:deps || true;
            cd /app/foldy-operator;
            docker build
              -f build/Dockerfile.deps
              -t foldy/foldy-operator:deps
              --cache-from foldy/foldy-operator:deps
              . ;
            docker push foldy/foldy-operator:deps;
            docker build
              -f build/Dockerfile
              -t foldy/foldy-operator:$commit
              . ;
            docker push foldy/foldy-operator:$commit;
          ]
        env:
          - name: commit
            value: "{{inputs.parameters.commit}}"
          - name: DOCKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: docker-creds
                key: username
          - name: DOCKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: docker-creds
                key: password
          - name: DOCKER_HOST # the docker daemon can be access on the standard port on localhost
            value: 127.0.0.1
      sidecars:
        - name: dind
          image: docker:18.09.6-dind # Docker already provides an image for running a Docker daemon
          securityContext:
            privileged: true # the Docker daemon can only run in a privileged container
          # mirrorVolumeMounts will mount the same volumes specified in the main container
          # to the sidecar (including artifacts), at the same mountPaths. This enables
          # dind daemon to (partially) see the same filesystem as the main container in
          # order to use features such as docker volume binding.
          mirrorVolumeMounts: true
    - name: dashboard
      serviceAccountName: argo-events-sa
      inputs:
        parameters:
          - name: commit
        artifacts:
          - name: source
            path: /app
            git:
              repo: https://github.com/foldy-project/foldy-operator.git
      container:
        image: docker:18.09.6
        command: [sh, -c] #
        args:
          [
            echo $commit;
            until docker ps;
              do sleep 3;
            done;
            set -e;
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin;
            docker pull foldy/dashboard:deps || true;
            cd /app/dashboard;
            docker build
              -f Dockerfile.deps
              -t foldy/dashboard:deps
              --cache-from foldy/dashboard:deps
              . ;
            docker push foldy/dashboard:deps;
            docker build -t foldy/dashboard:$commit . ;
            docker push foldy/dashboard:$commit;
          ]
        env:
          - name: commit
            value: "{{inputs.parameters.commit}}"
          - name: DOCKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: docker-creds
                key: username
          - name: DOCKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: docker-creds
                key: password
          - name: DOCKER_HOST # the docker daemon can be access on the standard port on localhost
            value: 127.0.0.1
      sidecars:
        - name: dind
          image: docker:18.09.6-dind # Docker already provides an image for running a Docker daemon
          securityContext:
            privileged: true # the Docker daemon can only run in a privileged container
          # mirrorVolumeMounts will mount the same volumes specified in the main container
          # to the sidecar (including artifacts), at the same mountPaths. This enables
          # dind daemon to (partially) see the same filesystem as the main container in
          # order to use features such as docker volume binding.
          mirrorVolumeMounts: true
    - name: sync
      serviceAccountName: argo-events-sa
      inputs:
        parameters:
          - name: commit
          - name: modified
      container:
        image: argoproj/argocd:latest
        command: [bash, -c]
        args: [
          echo $modified;
          argocd app set foldy-ci -p operator.image=foldy/foldy-operator:$commit;
          argocd app set foldy-ci -p dashboard.image=foldy/dashboard:$commit;
          argocd app sync foldy-ci;
          ]
        env:
          - name: commit
            value: "{{inputs.parameters.commit}}"
          - name: ARGOCD_SERVER
            value: argocd.foldy.dev
          - name: ARGOCD_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: argo-token
                key: token




